/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Laadpaal = {
  _id: string;
  _type: "laadpaal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  naam?: string;
  ocm_id?: string;
  locatie?: Geopoint;
  max_kw?: number;
  netwerk?:
    "Fastned" | "Ionity" | "Allego" | "Shell Recharge" | "Tesla" | "Overig";
  connector_types?: Array<string>;
  notitie?: string;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CampingReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "camping";
};

export type Gids = {
  _id: string;
  _type: "gids";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel?: string;
  slug?: Slug;
  hook?: string;
  hero_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          affiliate?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        camping?: CampingReference;
        redactionele_review?: string;
        cta_tekst?: string;
        _type: "campingCard";
        _key: string;
      }
    | {
        titel?: string;
        afstand_km?: number;
        verwacht_verbruik?: string;
        laadtip?: string;
        campings?: Array<
          {
            _key: string;
          } & CampingReference
        >;
        _type: "etappeBlok";
        _key: string;
      }
    | {
        titel?: string;
        items?: Array<{
          label?: string;
          affiliate_url?: string;
          _key: string;
        }>;
        _type: "checklist";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  seo_titel?: string;
  seo_beschrijving?: string;
  focus_keyword?: string;
  land?: string;
  geschikt_voor?: Array<string>;
  gepubliceerd_op?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Camping = {
  _id: string;
  _type: "camping";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  featured?: boolean;
  naam?: string;
  slug?: Slug;
  locatie?: Geopoint;
  land?:
    | "Nederland"
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Spanje"
    | "Oostenrijk"
    | "Zwitserland"
    | "Kroati\xEB";
  regio?: string;
  affiliate_link?: string;
  afbeeldingen?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  aantal_laders?: number;
  laadsnelheid?:
    | "3,7 kW (Schuko)"
    | "11 kW (Type 2)"
    | "22 kW (Type 2)"
    | "50 kW (DC)"
    | "150 kW+ (HPC)";
  netwerk?: string;
  laden_bij_tent?: boolean;
  snellader_in_buurt?: string;
  ev_notitie?: string;
  ev_geverifieerd_op?: string;
};

export type LaadpaalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "laadpaal";
};

export type Etappe = {
  _id: string;
  _type: "etappe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  naam?: string;
  slug?: Slug;
  afstand_km?: number;
  hoogteverschil_m?: number;
  extra_verbruik_procent?: number;
  rijdtips?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  campings?: Array<
    {
      _key: string;
    } & CampingReference
  >;
  laadpalen?: Array<
    {
      _key: string;
    } & LaadpaalReference
  >;
  polyline?: string;
};

export type EtappeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "etappe";
};

export type Route = {
  _id: string;
  _type: "route";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  featured?: boolean;
  titel?: string;
  slug?: Slug;
  beschrijving?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  totale_km?: number;
  caravan_geschikt?: boolean;
  landen?: Array<string>;
  etappes?: Array<
    {
      _key: string;
    } & EtappeReference
  >;
  seo_titel?: string;
  seo_beschrijving?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | Laadpaal
  | Geopoint
  | SanityImageAssetReference
  | CampingReference
  | Gids
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Camping
  | LaadpaalReference
  | Etappe
  | EtappeReference
  | Route
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: app/sitemap.ts
// Variable: campingSlugsQuery
// Query: *[_type == "camping"]{ "slug": slug.current, "land": land, _updatedAt }
export type CampingSlugsQueryResult = Array<{
  slug: string | null;
  land:
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Kroati\xEB"
    | "Nederland"
    | "Oostenrijk"
    | "Spanje"
    | "Zwitserland"
    | null;
  _updatedAt: string;
}>;

// Source: app/sitemap.ts
// Variable: routeSlugsQuery
// Query: *[_type == "route"]{ "slug": slug.current, _updatedAt }
export type RouteSlugsQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: app/sitemap.ts
// Variable: gidsSlugsQuery
// Query: *[_type == "gids"]{ "slug": slug.current, _updatedAt }
export type GidsSlugsQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: app/sitemap.ts
// Variable: landenQuery
// Query: *[_type == "camping" && defined(land)]{ "land": land }
export type LandenQueryResult = Array<{
  land:
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Kroati\xEB"
    | "Nederland"
    | "Oostenrijk"
    | "Spanje"
    | "Zwitserland";
}>;

// Source: sanity/queries/campings.ts
// Variable: allCampingsQuery
// Query: *[_type == "camping"] | order(naam asc) {    _id,    naam,    slug,    locatie,    land,    regio,    affiliate_link,    "thumbnail": afbeeldingen[0],    aantal_laders,    laadsnelheid,    netwerk,    laden_bij_tent,    snellader_in_buurt,    ev_geverifieerd_op    }
export type AllCampingsQueryResult = Array<{
  _id: string;
  naam: string | null;
  slug: Slug | null;
  locatie: Geopoint | null;
  land:
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Kroati\xEB"
    | "Nederland"
    | "Oostenrijk"
    | "Spanje"
    | "Zwitserland"
    | null;
  regio: string | null;
  affiliate_link: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | null;
  aantal_laders: number | null;
  laadsnelheid:
    | "11 kW (Type 2)"
    | "150 kW+ (HPC)"
    | "22 kW (Type 2)"
    | "3,7 kW (Schuko)"
    | "50 kW (DC)"
    | null;
  netwerk: string | null;
  laden_bij_tent: boolean | null;
  snellader_in_buurt: string | null;
  ev_geverifieerd_op: string | null;
}>;

// Source: sanity/queries/campings.ts
// Variable: campingBySlugQuery
// Query: *[_type == "camping" && slug.current == $slug][0] {    _id,    naam,    slug,    locatie,    land,    regio,    affiliate_link,    afbeeldingen,    aantal_laders,    laadsnelheid,    netwerk,    laden_bij_tent,    snellader_in_buurt,    ev_notitie,    ev_geverifieerd_op    }
export type CampingBySlugQueryResult = {
  _id: string;
  naam: string | null;
  slug: Slug | null;
  locatie: Geopoint | null;
  land:
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Kroati\xEB"
    | "Nederland"
    | "Oostenrijk"
    | "Spanje"
    | "Zwitserland"
    | null;
  regio: string | null;
  affiliate_link: string | null;
  afbeeldingen: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  aantal_laders: number | null;
  laadsnelheid:
    | "11 kW (Type 2)"
    | "150 kW+ (HPC)"
    | "22 kW (Type 2)"
    | "3,7 kW (Schuko)"
    | "50 kW (DC)"
    | null;
  netwerk: string | null;
  laden_bij_tent: boolean | null;
  snellader_in_buurt: string | null;
  ev_notitie: string | null;
  ev_geverifieerd_op: string | null;
} | null;

// Source: sanity/queries/campings.ts
// Variable: allCampingSlugsQuery
// Query: *[_type == "camping"]{    "slug": slug.current,    "land": land  }
export type AllCampingSlugsQueryResult = Array<{
  slug: string | null;
  land:
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Kroati\xEB"
    | "Nederland"
    | "Oostenrijk"
    | "Spanje"
    | "Zwitserland"
    | null;
}>;

// Source: sanity/queries/campings.ts
// Variable: allLandenQuery
// Query: *[_type == "camping" && defined(land)] {    "land": land  }
export type AllLandenQueryResult = Array<{
  land:
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Kroati\xEB"
    | "Nederland"
    | "Oostenrijk"
    | "Spanje"
    | "Zwitserland";
}>;

// Source: sanity/queries/campings.ts
// Variable: campingsByLandQuery
// Query: *[_type == "camping" && land == $land] | order(naam asc) {    _id,    naam,    slug,    locatie,    land,    regio,    affiliate_link,    "thumbnail": afbeeldingen[0],    aantal_laders,    laadsnelheid,    netwerk,    laden_bij_tent,    snellader_in_buurt,    ev_geverifieerd_op  }
export type CampingsByLandQueryResult = Array<{
  _id: string;
  naam: string | null;
  slug: Slug | null;
  locatie: Geopoint | null;
  land:
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Kroati\xEB"
    | "Nederland"
    | "Oostenrijk"
    | "Spanje"
    | "Zwitserland"
    | null;
  regio: string | null;
  affiliate_link: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | null;
  aantal_laders: number | null;
  laadsnelheid:
    | "11 kW (Type 2)"
    | "150 kW+ (HPC)"
    | "22 kW (Type 2)"
    | "3,7 kW (Schuko)"
    | "50 kW (DC)"
    | null;
  netwerk: string | null;
  laden_bij_tent: boolean | null;
  snellader_in_buurt: string | null;
  ev_geverifieerd_op: string | null;
}>;

// Source: sanity/queries/gidsen.ts
// Variable: allGidsenQuery
// Query: *[_type == "gids"] | order(gepubliceerd_op desc) {    _id,    titel,    slug,    hook,    hero_image,    land,    geschikt_voor,    gepubliceerd_op,    focus_keyword,    // Tel het aantal camping cards in de body    "aantal_campings": count(body[_type == "campingCard"])    }
export type AllGidsenQueryResult = Array<{
  _id: string;
  titel: string | null;
  slug: Slug | null;
  hook: string | null;
  hero_image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  land: string | null;
  geschikt_voor: Array<string> | null;
  gepubliceerd_op: string | null;
  focus_keyword: string | null;
  aantal_campings: number | null;
}>;

// Source: sanity/queries/gidsen.ts
// Variable: gidsBySlugQuery
// Query: *[_type == "gids" && slug.current == $slug][0] {    _id,    titel,    slug,    hook,    hero_image,    land,    geschikt_voor,    gepubliceerd_op,    seo_titel,    seo_beschrijving,    focus_keyword,    body[] {        ...,        // Resolve camping references in campingCard blokken        _type == "campingCard" => {            ...,            camping-> {            naam,            slug,            land,            affiliate_link,            afbeeldingen,            aantal_laders,            laadsnelheid,            netwerk,            laden_bij_tent,            snellader_in_buurt            }        },        // Resolve camping references in etappeBlokken        _type == "etappeBlok" => {                ...,                campings[]-> {                _id,                naam,                slug,                "thumbnail": afbeeldingen[0],                aantal_laders,                laadsnelheid,                netwerk,                laden_bij_tent                }            }        }    }
export type GidsBySlugQueryResult = {
  _id: string;
  titel: string | null;
  slug: Slug | null;
  hook: string | null;
  hero_image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  land: string | null;
  geschikt_voor: Array<string> | null;
  gepubliceerd_op: string | null;
  seo_titel: string | null;
  seo_beschrijving: string | null;
  focus_keyword: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          affiliate?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        camping: {
          naam: string | null;
          slug: Slug | null;
          land:
            | "Belgi\xEB"
            | "Duitsland"
            | "Frankrijk"
            | "Itali\xEB"
            | "Kroati\xEB"
            | "Nederland"
            | "Oostenrijk"
            | "Spanje"
            | "Zwitserland"
            | null;
          affiliate_link: string | null;
          afbeeldingen: Array<{
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
            _key: string;
          }> | null;
          aantal_laders: number | null;
          laadsnelheid:
            | "11 kW (Type 2)"
            | "150 kW+ (HPC)"
            | "22 kW (Type 2)"
            | "3,7 kW (Schuko)"
            | "50 kW (DC)"
            | null;
          netwerk: string | null;
          laden_bij_tent: boolean | null;
          snellader_in_buurt: string | null;
        } | null;
        redactionele_review?: string;
        cta_tekst?: string;
        _type: "campingCard";
        _key: string;
      }
    | {
        titel?: string;
        items?: Array<{
          label?: string;
          affiliate_url?: string;
          _key: string;
        }>;
        _type: "checklist";
        _key: string;
      }
    | {
        titel?: string;
        afstand_km?: number;
        verwacht_verbruik?: string;
        laadtip?: string;
        campings: Array<{
          _id: string;
          naam: string | null;
          slug: Slug | null;
          thumbnail: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
            _key: string;
          } | null;
          aantal_laders: number | null;
          laadsnelheid:
            | "11 kW (Type 2)"
            | "150 kW+ (HPC)"
            | "22 kW (Type 2)"
            | "3,7 kW (Schuko)"
            | "50 kW (DC)"
            | null;
          netwerk: string | null;
          laden_bij_tent: boolean | null;
        }> | null;
        _type: "etappeBlok";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: sanity/queries/gidsen.ts
// Variable: allGidsSlugsQuery
// Query: *[_type == "gids"]{ "slug": slug.current }
export type AllGidsSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: sanity/queries/homepage.ts
// Variable: featuredRoutesQuery
// Query: *[_type == "route" && featured == true] | order(_updatedAt desc) [0...3] {    _id,    titel,    slug,    totale_km,    caravan_geschikt,    landen,    thumbnail,    seo_beschrijving,    "aantalEtappes": count(etappes),    "heeftLaadpaal": count(etappes[]->campings[]->[laadpaal_aanwezig == true]) > 0    }
export type FeaturedRoutesQueryResult = Array<{
  _id: string;
  titel: string | null;
  slug: Slug | null;
  totale_km: number | null;
  caravan_geschikt: boolean | null;
  landen: Array<string> | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo_beschrijving: string | null;
  aantalEtappes: number | null;
  heeftLaadpaal: boolean | null;
}>;

// Source: sanity/queries/homepage.ts
// Variable: featuredCampingsQuery
// Query: *[_type == "camping" && featured == true] | order(_updatedAt desc) [0...6] {    _id,    naam,    slug,    locatie,    land,    regio,    affiliate_link,    "thumbnail": afbeeldingen[0],    aantal_laders,    laadsnelheid,    netwerk,    laden_bij_tent,    snellader_in_buurt,    ev_geverifieerd_op    }
export type FeaturedCampingsQueryResult = Array<{
  _id: string;
  naam: string | null;
  slug: Slug | null;
  locatie: Geopoint | null;
  land:
    | "Belgi\xEB"
    | "Duitsland"
    | "Frankrijk"
    | "Itali\xEB"
    | "Kroati\xEB"
    | "Nederland"
    | "Oostenrijk"
    | "Spanje"
    | "Zwitserland"
    | null;
  regio: string | null;
  affiliate_link: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | null;
  aantal_laders: number | null;
  laadsnelheid:
    | "11 kW (Type 2)"
    | "150 kW+ (HPC)"
    | "22 kW (Type 2)"
    | "3,7 kW (Schuko)"
    | "50 kW (DC)"
    | null;
  netwerk: string | null;
  laden_bij_tent: boolean | null;
  snellader_in_buurt: string | null;
  ev_geverifieerd_op: string | null;
}>;

// Source: sanity/queries/routes.ts
// Variable: allRoutesQuery
// Query: *[_type == "route"] | order(totale_km asc) {        _id,        titel,        slug,        totale_km,        caravan_geschikt,        landen,        thumbnail,        seo_beschrijving,        "aantalEtappes": count(etappes),        "heeftLaadpaal": count(etappes[]->campings[]->[laadpaal_aanwezig == true]) > 0    }
export type AllRoutesQueryResult = Array<{
  _id: string;
  titel: string | null;
  slug: Slug | null;
  totale_km: number | null;
  caravan_geschikt: boolean | null;
  landen: Array<string> | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo_beschrijving: string | null;
  aantalEtappes: number | null;
  heeftLaadpaal: boolean | null;
}>;

// Source: sanity/queries/routes.ts
// Variable: routeBySlugQuery
// Query: *[_type == "route" && slug.current == $slug][0] {    _id,    titel,    slug,    beschrijving,    totale_km,    caravan_geschikt,    landen,    thumbnail,    seo_titel,    seo_beschrijving,    "etappes": etappes[]-> {        _id,        naam,        slug,        afstand_km,        hoogteverschil_m,        extra_verbruik_procent,        rijdtips,        polyline,        "campings": campings[]-> {            _id,            naam,            slug,            locatie,            "thumbnail": afbeeldingen[0],            aantal_laders,            laadsnelheid,            netwerk,            laden_bij_tent,            snellader_in_buurt        },        "laadpalen": laadpalen[]-> {            _id,            naam,            locatie,            max_kw,            netwerk,            connector_types        }    }}
export type RouteBySlugQueryResult = {
  _id: string;
  titel: string | null;
  slug: Slug | null;
  beschrijving: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  totale_km: number | null;
  caravan_geschikt: boolean | null;
  landen: Array<string> | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo_titel: string | null;
  seo_beschrijving: string | null;
  etappes: Array<{
    _id: string;
    naam: string | null;
    slug: Slug | null;
    afstand_km: number | null;
    hoogteverschil_m: number | null;
    extra_verbruik_procent: number | null;
    rijdtips: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    polyline: string | null;
    campings: Array<{
      _id: string;
      naam: string | null;
      slug: Slug | null;
      locatie: Geopoint | null;
      thumbnail: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      } | null;
      aantal_laders: number | null;
      laadsnelheid:
        | "11 kW (Type 2)"
        | "150 kW+ (HPC)"
        | "22 kW (Type 2)"
        | "3,7 kW (Schuko)"
        | "50 kW (DC)"
        | null;
      netwerk: string | null;
      laden_bij_tent: boolean | null;
      snellader_in_buurt: string | null;
    }> | null;
    laadpalen: Array<{
      _id: string;
      naam: string | null;
      locatie: Geopoint | null;
      max_kw: number | null;
      netwerk:
        | "Allego"
        | "Fastned"
        | "Ionity"
        | "Overig"
        | "Shell Recharge"
        | "Tesla"
        | null;
      connector_types: Array<string> | null;
    }> | null;
  }> | null;
} | null;

// Source: sanity/queries/routes.ts
// Variable: allRouteSlugsQuery
// Query: *[_type == "route"]{ "slug": slug.current }
export type AllRouteSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "camping"]{ "slug": slug.current, "land": land, _updatedAt }\n': CampingSlugsQueryResult;
    '\n  *[_type == "route"]{ "slug": slug.current, _updatedAt }\n': RouteSlugsQueryResult;
    '\n  *[_type == "gids"]{ "slug": slug.current, _updatedAt }\n': GidsSlugsQueryResult;
    '\n  *[_type == "camping" && defined(land)]{ "land": land }\n': LandenQueryResult;
    '\n  *[_type == "camping"] | order(naam asc) {\n    _id,\n    naam,\n    slug,\n    locatie,\n    land,\n    regio,\n    affiliate_link,\n    "thumbnail": afbeeldingen[0],\n    aantal_laders,\n    laadsnelheid,\n    netwerk,\n    laden_bij_tent,\n    snellader_in_buurt,\n    ev_geverifieerd_op\n    }\n': AllCampingsQueryResult;
    '\n  *[_type == "camping" && slug.current == $slug][0] {\n    _id,\n    naam,\n    slug,\n    locatie,\n    land,\n    regio,\n    affiliate_link,\n    afbeeldingen,\n    aantal_laders,\n    laadsnelheid,\n    netwerk,\n    laden_bij_tent,\n    snellader_in_buurt,\n    ev_notitie,\n    ev_geverifieerd_op\n    }\n': CampingBySlugQueryResult;
    '\n  *[_type == "camping"]{\n    "slug": slug.current,\n    "land": land\n  }\n': AllCampingSlugsQueryResult;
    '\n  *[_type == "camping" && defined(land)] {\n    "land": land\n  }\n': AllLandenQueryResult;
    '\n  *[_type == "camping" && land == $land] | order(naam asc) {\n    _id,\n    naam,\n    slug,\n    locatie,\n    land,\n    regio,\n    affiliate_link,\n    "thumbnail": afbeeldingen[0],\n    aantal_laders,\n    laadsnelheid,\n    netwerk,\n    laden_bij_tent,\n    snellader_in_buurt,\n    ev_geverifieerd_op\n  }\n': CampingsByLandQueryResult;
    '\n  *[_type == "gids"] | order(gepubliceerd_op desc) {\n    _id,\n    titel,\n    slug,\n    hook,\n    hero_image,\n    land,\n    geschikt_voor,\n    gepubliceerd_op,\n    focus_keyword,\n    // Tel het aantal camping cards in de body\n    "aantal_campings": count(body[_type == "campingCard"])\n    }\n': AllGidsenQueryResult;
    '\n  *[_type == "gids" && slug.current == $slug][0] {\n    _id,\n    titel,\n    slug,\n    hook,\n    hero_image,\n    land,\n    geschikt_voor,\n    gepubliceerd_op,\n    seo_titel,\n    seo_beschrijving,\n    focus_keyword,\n    body[] {\n        ...,\n        // Resolve camping references in campingCard blokken\n        _type == "campingCard" => {\n            ...,\n            camping-> {\n            naam,\n            slug,\n            land,\n            affiliate_link,\n            afbeeldingen,\n            aantal_laders,\n            laadsnelheid,\n            netwerk,\n            laden_bij_tent,\n            snellader_in_buurt\n            }\n        },\n        // Resolve camping references in etappeBlokken\n        _type == "etappeBlok" => {\n                ...,\n                campings[]-> {\n                _id,\n                naam,\n                slug,\n                "thumbnail": afbeeldingen[0],\n                aantal_laders,\n                laadsnelheid,\n                netwerk,\n                laden_bij_tent\n                }\n            }\n        }\n    }\n': GidsBySlugQueryResult;
    '\n  *[_type == "gids"]{ "slug": slug.current }\n': AllGidsSlugsQueryResult;
    '\n  *[_type == "route" && featured == true] | order(_updatedAt desc) [0...3] {\n    _id,\n    titel,\n    slug,\n    totale_km,\n    caravan_geschikt,\n    landen,\n    thumbnail,\n    seo_beschrijving,\n    "aantalEtappes": count(etappes),\n    "heeftLaadpaal": count(etappes[]->campings[]->[laadpaal_aanwezig == true]) > 0\n    }\n': FeaturedRoutesQueryResult;
    '\n  *[_type == "camping" && featured == true] | order(_updatedAt desc) [0...6] {\n    _id,\n    naam,\n    slug,\n    locatie,\n    land,\n    regio,\n    affiliate_link,\n    "thumbnail": afbeeldingen[0],\n    aantal_laders,\n    laadsnelheid,\n    netwerk,\n    laden_bij_tent,\n    snellader_in_buurt,\n    ev_geverifieerd_op\n    }\n': FeaturedCampingsQueryResult;
    '\n  *[_type == "route"] | order(totale_km asc) {\n        _id,\n        titel,\n        slug,\n        totale_km,\n        caravan_geschikt,\n        landen,\n        thumbnail,\n        seo_beschrijving,\n        "aantalEtappes": count(etappes),\n        "heeftLaadpaal": count(etappes[]->campings[]->[laadpaal_aanwezig == true]) > 0\n    }\n': AllRoutesQueryResult;
    '\n  *[_type == "route" && slug.current == $slug][0] {\n    _id,\n    titel,\n    slug,\n    beschrijving,\n    totale_km,\n    caravan_geschikt,\n    landen,\n    thumbnail,\n    seo_titel,\n    seo_beschrijving,\n    "etappes": etappes[]-> {\n        _id,\n        naam,\n        slug,\n        afstand_km,\n        hoogteverschil_m,\n        extra_verbruik_procent,\n        rijdtips,\n        polyline,\n        "campings": campings[]-> {\n            _id,\n            naam,\n            slug,\n            locatie,\n            "thumbnail": afbeeldingen[0],\n            aantal_laders,\n            laadsnelheid,\n            netwerk,\n            laden_bij_tent,\n            snellader_in_buurt\n        },\n        "laadpalen": laadpalen[]-> {\n            _id,\n            naam,\n            locatie,\n            max_kw,\n            netwerk,\n            connector_types\n        }\n    }\n}\n': RouteBySlugQueryResult;
    '\n  *[_type == "route"]{ "slug": slug.current }\n': AllRouteSlugsQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
